title: "Продуктовый практикум"
description: "Авторские эссе - статьи, вдохновлённые опытом и практикой использования и исследования продуктов и сервисов."
theme: minima # Встроенная тема, можно выбрать любую другую
